<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="MilestoneForm.aspx.cs" Inherits="lscorporation.Pages.Forms.Basic.MilestoneForm" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Milestone Form</title>
</head>
<body>
    <form id="form1" runat="server">
        <h2>Milestone Management</h2>

        <!-- Insert Milestone -->
        <asp:FormView ID="FormView1" runat="server"
            DataSourceID="SqlDataSource1"
            DefaultMode="Insert"
            RenderOuterTable="false">
            <InsertItemTemplate>
                <table>
                    <tr><td>Milestone ID:</td><td><asp:TextBox runat="server" Text='<%# Bind("MILESTONE_ID") %>' /></td></tr>
                    <tr><td>Project ID:</td><td><asp:TextBox runat="server" Text='<%# Bind("PROJECT_ID") %>' /></td></tr>
                    <tr><td>Milestone Name:</td><td><asp:TextBox runat="server" Text='<%# Bind("MILESTONE_NAME") %>' /></td></tr>
                    <tr><td>Due Date:</td><td><asp:TextBox runat="server" Text='<%# Bind("MILESTONE_DUE_DATE") %>' /></td></tr>
                    <tr>
                        <td colspan="2">
                            <asp:Button runat="server" CommandName="Insert" Text="Insert" />
                            <asp:Button runat="server" CommandName="Cancel" Text="Cancel" />
                        </td>
                    </tr>
                </table>
            </InsertItemTemplate>
        </asp:FormView>

        <hr />

        <!-- GridView to View/Edit/Delete -->
        <asp:GridView ID="GridView1" runat="server"
            DataSourceID="SqlDataSource1"
            AutoGenerateColumns="False"
            DataKeyNames="MILESTONE_ID"
            AutoGenerateEditButton="true"
            AutoGenerateDeleteButton="true"
            AllowPaging="true"
            AllowSorting="true"
            Width="100%">
            <Columns>
                <asp:BoundField DataField="MILESTONE_ID" HeaderText="Milestone ID" ReadOnly="true" />
                <asp:BoundField DataField="PROJECT_ID" HeaderText="Project ID" />
                <asp:BoundField DataField="MILESTONE_NAME" HeaderText="Name" />
                <asp:BoundField DataField="MILESTONE_DUE_DATE" HeaderText="Due Date" />
            </Columns>
        </asp:GridView>

        <!-- SqlDataSource for MILESTONES -->
        <asp:SqlDataSource ID="SqlDataSource1" runat="server"
            ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
            ProviderName="System.Data.OracleClient"
            SelectCommand="SELECT * FROM MILESTONES ORDER BY MILESTONE_ID"
            InsertCommand="INSERT INTO MILESTONES (MILESTONE_ID, PROJECT_ID, MILESTONE_NAME, MILESTONE_DUE_DATE) VALUES (:MILESTONE_ID, :PROJECT_ID, :MILESTONE_NAME, :MILESTONE_DUE_DATE)"
            UpdateCommand="UPDATE MILESTONES SET PROJECT_ID=:PROJECT_ID, MILESTONE_NAME=:MILESTONE_NAME, MILESTONE_DUE_DATE=:MILESTONE_DUE_DATE WHERE MILESTONE_ID=:MILESTONE_ID"
            DeleteCommand="DELETE FROM MILESTONES WHERE MILESTONE_ID=:MILESTONE_ID">

            <InsertParameters>
                <asp:Parameter Name="MILESTONE_ID" Type="String" />
                <asp:Parameter Name="PROJECT_ID" Type="String" />
                <asp:Parameter Name="MILESTONE_NAME" Type="String" />
                <asp:Parameter Name="MILESTONE_DUE_DATE" Type="DateTime" />
            </InsertParameters>

            <UpdateParameters>
                <asp:Parameter Name="PROJECT_ID" Type="String" />
                <asp:Parameter Name="MILESTONE_NAME" Type="String" />
                <asp:Parameter Name="MILESTONE_DUE_DATE" Type="DateTime" />
                <asp:Parameter Name="MILESTONE_ID" Type="String" />
            </UpdateParameters>

            <DeleteParameters>
                <asp:Parameter Name="MILESTONE_ID" Type="String" />
            </DeleteParameters>
        </asp:SqlDataSource>

    </form>
</body>
</html>
