<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ProjectForm.aspx.cs" Inherits="lscorporation.Pages.Forms.Basic.ProjectForm" %>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server"><title>Project Management</title></head>
<body>
    <form id="form1" runat="server">
        <h2>Project Management</h2>

        <asp:FormView ID="FormView1" runat="server" DataSourceID="SqlDataSource1" DefaultMode="Insert" RenderOuterTable="false">
            <InsertItemTemplate>
                <table>
                    <tr><td>Project ID:</td><td><asp:TextBox runat="server" Text='<%# Bind("PROJECT_ID") %>' /></td></tr>
                    <tr><td>Name:</td><td><asp:TextBox runat="server" Text='<%# Bind("PROJECT_NAME") %>' /></td></tr>
                    <tr><td>Start Date:</td><td><asp:TextBox runat="server" Text='<%# Bind("PROJECT_START_DATE") %>' /></td></tr>
                    <tr><td>Due Date:</td><td><asp:TextBox runat="server" Text='<%# Bind("PROJECT_DUE_DATE") %>' /></td></tr>
                    <tr><td>Status:</td><td><asp:TextBox runat="server" Text='<%# Bind("PROJECT_STATUS") %>' /></td></tr>
                    <tr><td colspan="2"><asp:Button runat="server" CommandName="Insert" Text="Insert" /></td></tr>
                </table>
            </InsertItemTemplate>
        </asp:FormView>

        <asp:GridView ID="GridView1" runat="server" DataSourceID="SqlDataSource1" AutoGenerateColumns="False" DataKeyNames="PROJECT_ID" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true">
            <Columns>
                <asp:BoundField DataField="PROJECT_ID" HeaderText="ID" ReadOnly="true" />
                <asp:BoundField DataField="PROJECT_NAME" HeaderText="Name" />
                <asp:BoundField DataField="PROJECT_START_DATE" HeaderText="Start Date" />
                <asp:BoundField DataField="PROJECT_DUE_DATE" HeaderText="Due Date" />
                <asp:BoundField DataField="PROJECT_STATUS" HeaderText="Status" />
            </Columns>
        </asp:GridView>

        <asp:SqlDataSource ID="SqlDataSource1" runat="server"
            ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
            ProviderName="System.Data.OracleClient"
            SelectCommand="SELECT * FROM PROJECTS"
            InsertCommand="INSERT INTO PROJECTS (PROJECT_ID, PROJECT_NAME, PROJECT_START_DATE, PROJECT_DUE_DATE, PROJECT_STATUS) VALUES (:PROJECT_ID, :PROJECT_NAME, :PROJECT_START_DATE, :PROJECT_DUE_DATE, :PROJECT_STATUS)"
            UpdateCommand="UPDATE PROJECTS SET PROJECT_NAME=:PROJECT_NAME, PROJECT_START_DATE=:PROJECT_START_DATE, PROJECT_DUE_DATE=:PROJECT_DUE_DATE, PROJECT_STATUS=:PROJECT_STATUS WHERE PROJECT_ID=:PROJECT_ID"
            DeleteCommand="DELETE FROM PROJECTS WHERE PROJECT_ID=:PROJECT_ID">
            <InsertParameters>
                <asp:Parameter Name="PROJECT_ID" Type="String" />
                <asp:Parameter Name="PROJECT_NAME" Type="String" />
                <asp:Parameter Name="PROJECT_START_DATE" Type="DateTime" />
                <asp:Parameter Name="PROJECT_DUE_DATE" Type="DateTime" />
                <asp:Parameter Name="PROJECT_STATUS" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="PROJECT_NAME" Type="String" />
                <asp:Parameter Name="PROJECT_START_DATE" Type="DateTime" />
                <asp:Parameter Name="PROJECT_DUE_DATE" Type="DateTime" />
                <asp:Parameter Name="PROJECT_STATUS" Type="String" />
                <asp:Parameter Name="PROJECT_ID" Type="String" />
            </UpdateParameters>
            <DeleteParameters>
                <asp:Parameter Name="PROJECT_ID" Type="String" />
            </DeleteParameters>
        </asp:SqlDataSource>
    </form>
</body>
</html>
