<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="SubTaskForm.aspx.cs" Inherits="lscorporation.Pages.Forms.Basic.SubTaskForm" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>SubTask Management</title>
</head>
<body>
    <form id="form1" runat="server">
        <h2>SubTask Management</h2>

        <!-- FormView for INSERT -->
        <asp:FormView ID="FormView1" runat="server"
            DataSourceID="SqlDataSource1"
            DefaultMode="Insert"
            RenderOuterTable="false">
            <InsertItemTemplate>
                <table>
                    <tr><td>SubTask ID:</td><td><asp:TextBox runat="server" Text='<%# Bind("SUBTASK_ID") %>' /></td></tr>
                    <tr><td>Task ID:</td><td><asp:TextBox runat="server" Text='<%# Bind("TASK_ID") %>' /></td></tr>
                    <tr><td>SubTask Name:</td><td><asp:TextBox runat="server" Text='<%# Bind("SUBTASK_NAME") %>' /></td></tr>
                    <tr><td>Description:</td><td><asp:TextBox runat="server" Text='<%# Bind("SUBTASK_DESCRIPTION") %>' /></td></tr>
                    <tr><td>Status:</td><td><asp:TextBox runat="server" Text='<%# Bind("SUBTASK_STATUS") %>' /></td></tr>
                    <tr>
                        <td colspan="2">
                            <asp:Button runat="server" CommandName="Insert" Text="Insert" />
                            <asp:Button runat="server" CommandName="Cancel" Text="Cancel" />
                        </td>
                    </tr>
                </table>
            </InsertItemTemplate>
        </asp:FormView>

        <hr />

        <!-- GridView to List/Update/Delete SubTasks -->
        <asp:GridView ID="GridView1" runat="server"
            DataSourceID="SqlDataSource1"
            AutoGenerateColumns="False"
            DataKeyNames="SUBTASK_ID"
            AutoGenerateEditButton="true"
            AutoGenerateDeleteButton="true"
            AllowPaging="true"
            AllowSorting="true"
            Width="100%">
            <Columns>
                <asp:BoundField DataField="SUBTASK_ID" HeaderText="SubTask ID" ReadOnly="true" />
                <asp:BoundField DataField="TASK_ID" HeaderText="Task ID" />
                <asp:BoundField DataField="SUBTASK_NAME" HeaderText="Name" />
                <asp:BoundField DataField="SUBTASK_DESCRIPTION" HeaderText="Description" />
                <asp:BoundField DataField="SUBTASK_STATUS" HeaderText="Status" />
            </Columns>
        </asp:GridView>

        <!-- SqlDataSource for SUBTASK table -->
        <asp:SqlDataSource ID="SqlDataSource1" runat="server"
            ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
            ProviderName="System.Data.OracleClient"
            SelectCommand="SELECT * FROM SUBTASKS ORDER BY SUBTASK_ID"
            InsertCommand="INSERT INTO SUBTASKS (SUBTASK_ID, TASK_ID, SUBTASK_NAME, SUBTASK_DESCRIPTION, SUBTASK_STATUS) VALUES (:SUBTASK_ID, :TASK_ID, :SUBTASK_NAME, :SUBTASK_DESCRIPTION, :SUBTASK_STATUS)"
            UpdateCommand="UPDATE SUBTASKS SET TASK_ID=:TASK_ID, SUBTASK_NAME=:SUBTASK_NAME, SUBTASK_DESCRIPTION=:SUBTASK_DESCRIPTION, SUBTASK_STATUS=:SUBTASK_STATUS WHERE SUBTASK_ID=:SUBTASK_ID"
            DeleteCommand="DELETE FROM SUBTASKS WHERE SUBTASK_ID=:SUBTASK_ID">

            <InsertParameters>
                <asp:Parameter Name="SUBTASK_ID" Type="String" />
                <asp:Parameter Name="TASK_ID" Type="String" />
                <asp:Parameter Name="SUBTASK_NAME" Type="String" />
                <asp:Parameter Name="SUBTASK_DESCRIPTION" Type="String" />
                <asp:Parameter Name="SUBTASK_STATUS" Type="String" />
            </InsertParameters>

            <UpdateParameters>
                <asp:Parameter Name="TASK_ID" Type="String" />
                <asp:Parameter Name="SUBTASK_NAME" Type="String" />
                <asp:Parameter Name="SUBTASK_DESCRIPTION" Type="String" />
                <asp:Parameter Name="SUBTASK_STATUS" Type="String" />
                <asp:Parameter Name="SUBTASK_ID" Type="String" />
            </UpdateParameters>

            <DeleteParameters>
                <asp:Parameter Name="SUBTASK_ID" Type="String" />
            </DeleteParameters>
        </asp:SqlDataSource>

    </form>
</body>
</html>
