<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="TaskForm.aspx.cs" Inherits="lscorporation.Pages.Forms.Basic.TaskForm" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Task Form</title>
</head>
<body>
    <form id="form1" runat="server">
        <h2>Task Management</h2>

        <!-- FormView for Insert -->
        <asp:FormView ID="FormView1" runat="server"
            DataSourceID="SqlDataSource1"
            DefaultMode="Insert"
            RenderOuterTable="false">
            <InsertItemTemplate>
                <table>
                    <tr><td>Task ID:</td><td><asp:TextBox runat="server" Text='<%# Bind("TASK_ID") %>' /></td></tr>
                    <tr><td>Project ID:</td><td><asp:TextBox runat="server" Text='<%# Bind("PROJECT_ID") %>' /></td></tr>
                    <tr><td>Task Name:</td><td><asp:TextBox runat="server" Text='<%# Bind("TASK_NAME") %>' /></td></tr>
                    <tr><td>Start Date:</td><td><asp:TextBox runat="server" Text='<%# Bind("TASK_START_DATE") %>' /></td></tr>
                    <tr><td>Due Date:</td><td><asp:TextBox runat="server" Text='<%# Bind("TASK_DUE_DATE") %>' /></td></tr>
                    <tr><td>Status:</td><td><asp:TextBox runat="server" Text='<%# Bind("TASK_STATUS") %>' /></td></tr>
                    <tr>
                        <td colspan="2">
                            <asp:Button runat="server" CommandName="Insert" Text="Insert" />
                            <asp:Button runat="server" CommandName="Cancel" Text="Cancel" />
                        </td>
                    </tr>
                </table>
            </InsertItemTemplate>
        </asp:FormView>

        <hr />

        <!-- GridView for View/Update/Delete -->
        <asp:GridView ID="GridView1" runat="server"
            DataSourceID="SqlDataSource1"
            AutoGenerateColumns="False"
            DataKeyNames="TASK_ID"
            AutoGenerateEditButton="true"
            AutoGenerateDeleteButton="true"
            AllowPaging="true"
            AllowSorting="true"
            Width="100%">
            <Columns>
                <asp:BoundField DataField="TASK_ID" HeaderText="Task ID" ReadOnly="True" />
                <asp:BoundField DataField="PROJECT_ID" HeaderText="Project ID" />
                <asp:BoundField DataField="TASK_NAME" HeaderText="Task Name" />
                <asp:BoundField DataField="TASK_START_DATE" HeaderText="Start Date" />
                <asp:BoundField DataField="TASK_DUE_DATE" HeaderText="Due Date" />
                <asp:BoundField DataField="TASK_STATUS" HeaderText="Status" />
            </Columns>
        </asp:GridView>

        <!-- SqlDataSource for TASKS -->
        <asp:SqlDataSource ID="SqlDataSource1" runat="server"
            ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
            ProviderName="System.Data.OracleClient"
            SelectCommand="SELECT * FROM TASKS ORDER BY TASK_ID"
            InsertCommand="INSERT INTO TASKS (TASK_ID, PROJECT_ID, TASK_NAME, TASK_START_DATE, TASK_DUE_DATE, TASK_STATUS) VALUES (:TASK_ID, :PROJECT_ID, :TASK_NAME, :TASK_START_DATE, :TASK_DUE_DATE, :TASK_STATUS)"
            UpdateCommand="UPDATE TASKS SET PROJECT_ID=:PROJECT_ID, TASK_NAME=:TASK_NAME, TASK_START_DATE=:TASK_START_DATE, TASK_DUE_DATE=:TASK_DUE_DATE, TASK_STATUS=:TASK_STATUS WHERE TASK_ID=:TASK_ID"
            DeleteCommand="DELETE FROM TASKS WHERE TASK_ID=:TASK_ID">

            <InsertParameters>
                <asp:Parameter Name="TASK_ID" Type="String" />
                <asp:Parameter Name="PROJECT_ID" Type="String" />
                <asp:Parameter Name="TASK_NAME" Type="String" />
                <asp:Parameter Name="TASK_START_DATE" Type="DateTime" />
                <asp:Parameter Name="TASK_DUE_DATE" Type="DateTime" />
                <asp:Parameter Name="TASK_STATUS" Type="String" />
            </InsertParameters>

            <UpdateParameters>
                <asp:Parameter Name="PROJECT_ID" Type="String" />
                <asp:Parameter Name="TASK_NAME" Type="String" />
                <asp:Parameter Name="TASK_START_DATE" Type="DateTime" />
                <asp:Parameter Name="TASK_DUE_DATE" Type="DateTime" />
                <asp:Parameter Name="TASK_STATUS" Type="String" />
                <asp:Parameter Name="TASK_ID" Type="String" />
            </UpdateParameters>

            <DeleteParameters>
                <asp:Parameter Name="TASK_ID" Type="String" />
            </DeleteParameters>
        </asp:SqlDataSource>

    </form>
</body>
</html>
